; 国家选择组（主组）
custom_proxy_group=🚀 国家选择`select`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT`[]🇸🇬 狮城自动`[]🇭🇰 香港自动`[]🇹🇼 台湾自动`[]🇺🇲 美国自动`[]🇯🇵 日本自动`[]🇰🇷 韩国自动`[]🌐 其他国家

; 地区自动测速
custom_proxy_group=🇸🇬 狮城自动`url-test`(新加坡|狮城|Singapore|SINGAPORE|SG[-_ ]|🇸🇬)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇭🇰 香港自动`url-test`(香港|Hong Kong|Hongkong|HONG KONG|HK[-_ ]|🇭🇰)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇹🇼 台湾自动`url-test`(台湾|Taiwan|TAIWAN|TW[-_ ]|🇹🇼)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇺🇲 美国自动`url-test`(美国|United States|UnitedStates|USA|US[-_ ]|America|AMERICA|🇺🇸)`http://www.gstatic.com/generate_204`300,,250
custom_proxy_group=🇯🇵 日本自动`url-test`(日本|Japan|JAPAN|JP[-_ ]|Tokyo|TOKYO|东京|大阪|🇯🇵)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇰🇷 韩国自动`url-test`(韩国|Korea|KOREA|South Korea|SouthKorea|KOR|KR[-_ ]|首尔|Seoul|🇰🇷)`http://www.gstatic.com/generate_204`300,,150

; 其他国家
custom_proxy_group=🌐 其他国家`url-test`^(?!(.*(新加坡|狮城|Singapore|SINGAPORE|SG[-_ ]|🇸🇬|香港|Hong Kong|Hongkong|HONG KONG|HK[-_ ]|🇭🇰|台湾|Taiwan|TAIWAN|TW[-_ ]|🇹🇼|美国|United States|UnitedStates|USA|US[-_ ]|America|AMERICA|🇺🇸|日本|Japan|JAPAN|JP[-_ ]|Tokyo|TOKYO|东京|大阪|🇯🇵|韩国|Korea|KOREA|South Korea|SouthKorea|KOR|KR[-_ ]|首尔|Seoul|🇰🇷))).*$`http://www.gstatic.com/generate_204`300,,200

; 自动选择（全局测速）
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,150

; 手动切换
custom_proxy_group=🚀 手动切换`select`.*

; 规则集（已将主组改为 🚀 国家选择）
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/force-direct.list
ruleset=🚀 国家选择,https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/force-proxy.list
ruleset=DIRECT,https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/acl/cn-domains.txt
ruleset=🚀 国家选择,https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/acl/gfwlist.txt
ruleset=DIRECT,[]GEOIP,CN
ruleset=🚀 国家选择,[]MATCH